name: Generate xml sitemap

on:
  push:
    branches: [ master ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://ethan-robert.xyz/

    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

    - name: Add sitemap to the repo
      run: |
	      git config --global user.name "Ethan Robert" 
	      git config --global user.email "ethan.rbrt90@gmail.com"
	      git add sitemap.xml
	      git commit -m "Update sitemap"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
	      github_token: ${{ secrets.GITHUB_TOKEN }}
